### ISSUE TITLE
Odd `-lOFF` flags in resulting Makefile

### ISSUE THREAD

**Issue by anthony-cros** [ethereum/libweb3core#23]
See description at https://doublethinkco.wordpress.com/2015/10/14/porting-ethereum-tizen-cross-builds-by-anthony-cros-14th-october-2015/ and the corresponding workaround I use: https://github.com/doublethinkco/sandbox/blob/0b4162e1005fa87371c6c4f01b60ff7221a80264/cpp-ethereum/scripts/libweb3core/libweb3core.sh#L74

EDIT: Needless to say they make the build crash if left untouched

**Comment by anthony-cros** [comment]
Actually, that probably has to do with my using these flags when running `cmake`:

```
cmake \
  ... \
  -DUtils_SECP256K1_LIBRARY=OFF \
  -DUtils_SCRYPT_LIBRARY=OFF
```

Are these library necessary?

**Comment by anthony-cros** [comment]
I ended up commenting out `set(LIBS secp256k1;scrypt)` in _webthree-helpers/cmake/FindUtils.cmake_, seems to work...

**Comment by bobsummerwill** [comment]
Hmm.   @anthony-cros Did we actually end up removing this hack?   I think we might have.   If so, let's close this ticket.

sec256k1 and scrypt certainly are needed.

**Comment by anthony-cros** [comment]
yes, it's all gone!
