### ISSUE TITLE
Peer discovery is broken

### ISSUE THREAD

**Issue by chriseth** [ethereum/libweb3core#42]
Especially behind NAT, the number of peers does not go above 1. This might also be a problem in the go node.

**Comment by bobsummerwill** [comment]
Closed because it is untrue, or because it just isn't addressable?

**Comment by chriseth** [comment]
Fixed here: https://github.com/ethereum/libweb3core/pull/45

**Comment by bobsummerwill** [comment]
Thanks for the clarification!
